import {
    MdAttachFile,
    MdCancel,
    MdCastForEducation,
    MdDashboard,
    MdDoNotDisturb,
    MdDoNotDisturbOn,
    MdKeyboardArrowLeft,
    MdKeyboardArrowRight,
    MdLocationPin,
    MdLogout,
    MdMoreTime,
    MdOutlineAttachEmail,
    MdOutlineCalculate,
    MdOutlineCancelPresentation,
    MdOutlineFamilyRestroom,
    MdOutlineFileUpload,
    MdOutlineFlight,
    MdOutlineHealthAndSafety,
    MdOutlinePendingActions,
    MdOutlineShield,
    MdSpaceDashboard,
    MdWorkHistory,
    MdOutlineLogout,
    MdKeyboardBackspace,
    MdPublish,
    MdTaskAlt,
    MdAnalytics,
    MdChevronRight,
    MdChevronLeft,
    MdDelete,
    MdChecklist,
    MdOutlinePlaylistAddCheckCircle,
    MdCancelPresentation,
} from "react-icons/md";
import {
    IoIosAddCircle,
    IoIosApps,
    IoIosListBox,
    IoIosLogIn,
    IoIosLogOut,
    IoIosWarning,
    IoMdAddCircleOutline,
    IoMdAttach,
    IoMdCheckboxOutline,
    IoMdCheckmarkCircleOutline,
} from "react-icons/io";
import { BsBuildings, BsExclamationTriangle, BsFillFilterSquareFill, BsFileEarmarkPdf } from "react-icons/bs";

import { ImCheckboxChecked, ImFire, ImHistory, ImStatsBars } from "react-icons/im";
import { CiTrash, CiEdit, CiViewList, CiCalendar, CiWarning, CiShoppingCart, CiTrophy, CiGift } from "react-icons/ci";

import { RxDashboard, RxHome } from "react-icons/rx";
import { TfiAngleLeft, TfiAngleRight, TfiMenuAlt } from "react-icons/tfi";
import { TiArrowSortedUp, TiArrowSortedDown } from "react-icons/ti";
import { SlOrganization } from "react-icons/sl";

import {
    LuBuilding,
    LuChartNoAxesCombined,
    LuClipboardCheck,
    LuDatabase,
    LuFileChartColumnIncreasing,
    LuFileCheck,
    LuFileClock,
    LuMoon,
    LuPencil,
    LuRepeat,
    LuShield,
    LuUpload,
    LuUserRound,
    LuDollarSign,
    LuRefreshCw,
    LuThumbsUp,
    LuThumbsDown,
    LuUser,
    LuFileText,
    LuListChecks,
    LuClock,
    LuMessageSquare,
    LuFilterX,
    LuUserRoundMinus,
    LuUserRoundX,
    LuUsersRound,
    LuFileBadge,
    LuFileUser,
} from "react-icons/lu";
import {
    FaRegCopy,
    FaArrowRight,
    FaCalendar,
    FaClock,
    FaFire,
    FaGreaterThan,
    FaMinusCircle,
    FaRegClock,
    FaAngleRight,
    FaRegStar,
    FaStar,
    FaRegFile,
    FaInfoCircle,
    FaExclamationCircle,
    FaClipboardList,
    FaRegBookmark,
    FaUndoAlt,
    FaChevronDown,
    FaPhoneAlt,
    FaRegCalendarCheck,
    FaUmbrellaBeach,
    FaHome,
    FaPassport,
    FaHospitalUser,
    FaRegPlusSquare,
    FaRegCalendarAlt,
    FaSearch,
    FaAngleDown,
    FaAngleUp,
    FaAngleLeft,
    FaArrowUp,
    FaArrowDown,
    FaUser,
    FaRegCheckCircle,
    FaMugHot,
    FaRegThumbsDown,
    FaRegCommentDots,
    FaPlus,
    FaRegFileAlt,
    FaHandsHelping,
    FaLockOpen,
    FaLock,
    FaRegThumbsUp,
    FaDollarSign,
    FaUserCheck,
    FaCheckCircle,
    FaTimesCircle,
    FaFileAlt,
    FaBalanceScale,
    FaMoneyBillWave,
    FaUserMinus,
    FaRegTimesCircle,
    FaRegEye,
    FaRegHeart,
    FaRupeeSign,
    FaTrophy,
    FaCog,
} from "react-icons/fa";

import { IoIosPeople, IoMdNotifications } from "react-icons/io";
import { CgDanger, CgFileDocument, CgProfile } from "react-icons/cg";
import {
    RiAddBoxLine,
    RiBarChartBoxFill,
    RiCheckboxBlankFill,
    RiCheckboxLine,
    RiCloseCircleFill,
    RiCloseCircleLine,
    RiDashboardHorizontalFill,
    RiEditBoxLine,
    RiFileUserLine,
    RiMoneyDollarCircleLine,
    RiShieldCheckFill,
    RiFileList3Line,
    RiArrowRightSLine,
    RiFileCloseLine,
} from "react-icons/ri";
import {
    AiFillCloseSquare,
    AiFillDelete,
    AiFillExclamationCircle,
    AiFillFilter,
    AiFillPayCircle,
    AiOutlineDelete,
    AiOutlineEdit,
    AiOutlinePayCircle,
    AiOutlineReconciliation,
    AiOutlineCheck,
    AiOutlineClose,
    AiTwotoneMail,
    AiTwotoneSetting,
    AiOutlineDatabase,
    AiFillLock,
    AiFillUnlock,
    AiOutlineThunderbolt,
    AiOutlineBank,
    AiOutlineFileExcel,
    AiOutlineDownload,
    AiOutlineInbox,
    AiOutlinePhone,
    AiOutlineCloudUpload,
    AiOutlineDashboard,
    AiOutlineSync,
    AiOutlineCrown,
} from "react-icons/ai";

import { VscLaw } from "react-icons/vsc";
import {
    GiArcheryTarget,
    GiArchiveRegister,
    GiDiamondTrophy,
    GiGraduateCap,
    GiPayMoney,
    GiReceiveMoney,
    GiStairsGoal,
    GiTakeMyMoney,
} from "react-icons/gi";
import { FcHighPriority } from "react-icons/fc";
import { GoAlertFill, GoChecklist, GoDotFill, GoFileBinary, GoCheck, GoCalendar, GoGear, GoPasskeyFill } from "react-icons/go";
import {
    FaArrowRightLong,
    FaArrowLeftLong,
    FaBuildingUser,
    FaCircleCheck,
    FaCircleMinus,
    FaCircleXmark,
    FaComputer,
    FaFileCircleCheck,
    FaFileShield,
    FaMoneyBillTransfer,
    FaRegStarHalfStroke,
    FaClockRotateLeft,
    FaArrowUpLong,
    FaArrowDownLong,
    FaRegFileLines,
    FaBuildingShield,
    FaArrowsRotate,
    FaArrowTrendUp,
    FaRegAddressCard,
    FaIndianRupeeSign,
} from "react-icons/fa6";
import {
    IoCameraReverseOutline,
    IoChevronBack,
    IoChevronBackCircleOutline,
    IoCreateOutline,
    IoEyeOutline,
    IoEyeSharp,
    IoFilterSharp,
    IoLocationOutline,
    IoNewspaperOutline,
    IoReceiptOutline,
    IoReload,
    IoSettingsOutline,
    IoShieldCheckmarkOutline,
    IoSpeedometerOutline,
    IoTimeOutline,
    IoWarningOutline,
} from "react-icons/io5";
import {
    FiDollarSign,
    FiDownload,
    FiGift,
    FiSun,
    FiUpload,
    FiUserCheck,
    FiUsers,
    FiUserMinus,
    FiUserX,
    FiFilePlus,
    FiSend,
    FiTool,
} from "react-icons/fi";
import {
    HiDocumentReport,
    HiOutlinePrinter,
    HiOutlineCurrencyDollar,
    HiOutlineLightningBolt,
    HiOutlineUser,
    HiOutlineClipboardList,
} from "react-icons/hi";
import { HiOutlineBuildingOffice2, HiOutlineSquares2X2 } from "react-icons/hi2";

import { Tooltip } from "antd";
import {
    BsArrowLeft,
    BsBank,
    BsBoxArrowInLeft,
    BsCurrencyDollar,
    BsEye,
    BsPersonCheck,
    BsPersonCheckFill,
    BsPersonVcard,
    BsExclamationCircle,
    BsThreeDotsVertical,
} from "react-icons/bs";
import { HiClipboardDocumentCheck, HiOutlineDocumentCheck } from "react-icons/hi2";
import {
    PiCheckCircleLight,
    PiClockClockwiseBold,
    PiCurrencyDollarBold,
    PiExportBold,
    PiListBulletsLight,
    PiSwapBold,
    PiWarningCircleLight,
    PiUsers,
} from "react-icons/pi";
import { FaTrashAlt, FaRegEdit } from "react-icons/fa";
import { BiEdit, BiExport, BiMaleFemale, BiMessageAdd } from "react-icons/bi";
import {
    TbBeach,
    TbCameraPlus,
    TbFileImport,
    TbLanguageKatakana,
    TbLockPassword,
    TbReport,
    TbSend,
    TbFileExport,
    TbUsersMinus,
    TbUserPlus,
} from "react-icons/tb";
import { TbReportSearch, TbSettingsDollar } from "react-icons/tb";
import { LiaFileImportSolid, LiaMoneyBillSolid, LiaMoneyCheckAltSolid } from "react-icons/lia";
import { GrCertificate, GrPowerReset, GrAttachment, GrStatusWarning, GrSubtractCircle } from "react-icons/gr";

import { SyncOutlined } from "@ant-design/icons";

function DynamicIconComponent({
    iconName = "StarOutlined",
    iconSize = "20px",
    color = "#08c",
    background = "",
    className,
    onclickIcon,
    onHoverIconEnter,
    onHoverIconLeave,
    style,
    showToolTip = false,
    toolTipLabel = "",
    toolTipColor = "#ffffff",
    disabled = false, // <-- added
    spin = false,
    toolTipPlacement = "top",
}) {
    const iconComponents = {
        TbSettingsDollar,
        AiOutlineCheck,
        AiOutlineClose,
        CiTrash,
        AiOutlineEdit,
        BiMessageAdd,
        IoEyeSharp,
        FaExclamationCircle,
        HiClipboardDocumentCheck,
        IoIosLogIn,
        IoIosLogOut,
        BsBoxArrowInLeft,
        MdOutlineAttachEmail,
        LuFileChartColumnIncreasing,
        MdChecklist,
        MdOutlinePlaylistAddCheckCircle,
        IoMdAddCircleOutline,
        RiFileUserLine,
        LuFileCheck,
        MdDelete,
        LuChartNoAxesCombined,
        IoTimeOutline,
        IoChevronBack,
        FiDollarSign,
        LuRepeat,
        FaRegEye,
        IoWarningOutline,
        FaRegCalendarCheck,
        TbReport,
        LuFileClock,
        PiCheckCircleLight,
        PiWarningCircleLight,
        TbBeach,
        FiDownload,
        AiFillDelete,
        BiEdit,
        GiArchiveRegister,
        IoCameraReverseOutline,
        TbCameraPlus,
        FaUmbrellaBeach,
        GiTakeMyMoney,
        GiPayMoney,
        FaBuildingUser,
        FaRegFileLines,
        GiStairsGoal,
        MdWorkHistory,
        ImHistory,
        FaBuildingShield,
        GrCertificate,
        FaHome,
        MdCastForEducation,
        FaPassport,
        BsPersonVcard,
        AiTwotoneSetting,
        FaComputer,
        TbLanguageKatakana,
        GiReceiveMoney,
        FaHospitalUser,
        MdOutlineFamilyRestroom,
        IoIosApps,
        BsBuildings,
        GiDiamondTrophy,
        MdOutlineFlight,
        RiAddBoxLine,
        FaRegPlusSquare,
        FaRegCalendarAlt,
        MdOutlineHealthAndSafety,
        MdKeyboardArrowLeft,
        MdKeyboardArrowRight,
        AiOutlineReconciliation,
        AiFillCloseSquare,
        FaMinusCircle,
        FaCircleMinus,
        BsArrowLeft,
        AiTwotoneMail,
        BiMaleFemale,
        FaPhoneAlt,
        BsBank,
        GiGraduateCap,
        FiGift,
        PiListBulletsLight,
        MdSpaceDashboard,
        FaFire,
        FaChevronDown,
        AiOutlineDownload,
        AiOutlineInbox,
        MdOutlineCancelPresentation,
        AiFillPayCircle,
        BsEye,
        AiOutlinePayCircle,
        IoMdNotifications,
        CgProfile,
        LuUpload,
        TbLockPassword,
        MdOutlinePendingActions,
        RiCheckboxLine,
        ImCheckboxChecked,
        RiCloseCircleFill,
        RiCloseCircleLine,
        RxDashboard,
        TfiMenuAlt,
        CiEdit,
        AiOutlineDelete,
        MdAttachFile,
        FiUpload,
        IoMdAttach,
        MdCancel,
        LuShield,
        FaGreaterThan,
        AiFillExclamationCircle,
        FaRegFile,
        VscLaw,
        RiEditBoxLine,
        RiCheckboxBlankFill,
        BsFileEarmarkPdf,
        IoIosListBox,
        CiCalendar,
        GiArcheryTarget,
        MdMoreTime,
        FcHighPriority,
        GoFileBinary,
        FaCircleCheck,
        MdDashboard,
        CiViewList,
        HiDocumentReport,
        FaFileShield,
        FaFileCircleCheck,
        LuPencil,
        BsPersonCheckFill,
        BsPersonCheck,
        FaCircleXmark,
        FaClock,
        FaTrashAlt,
        MdDoNotDisturbOn,
        MdDoNotDisturb,
        MdOutlineFileUpload,
        MdCancelPresentation,
        IoIosPeople,
        FaRegClock,
        CgDanger,
        CgFileDocument,
        FaArrowRightLong,
        FaArrowUpLong,
        FaArrowDown,
        FaArrowUp,
        FaArrowDownLong,
        FaCalendar,
        FaArrowRight,
        IoLocationOutline,
        ImFire,
        IoCreateOutline,
        MdKeyboardBackspace,
        FaAngleRight,
        AiOutlineFileExcel,
        TfiAngleRight,
        FaRegStar,
        FaStar,
        FaAngleDown,
        FaRegStarHalfStroke,
        IoIosWarning,
        LuUserRound,
        MdLocationPin,
        TbFileImport,
        FaInfoCircle,
        FiSun,
        LuMoon,
        FaClipboardList,
        HiOutlineDocumentCheck,
        PiCurrencyDollarBold,
        FaRegBookmark,
        FaUndoAlt,
        IoSettingsOutline,
        PiClockClockwiseBold,
        GoChecklist,
        IoReceiptOutline,
        IoReload,
        IoNewspaperOutline,
        IoMdCheckboxOutline,
        LuClipboardCheck,
        AiFillFilter,
        IoIosAddCircle,
        FaMoneyBillTransfer,
        FaArrowLeftLong,
        GoDotFill,
        FaClockRotateLeft,
        IoMdCheckmarkCircleOutline,
        LiaFileImportSolid,
        AiOutlineDatabase,
        LuDatabase,
        MdLogout,
        FiUsers,
        LuBuilding,
        BsCurrencyDollar,
        FaSearch,
        FaAngleUp,
        AiFillLock,
        AiFillUnlock,
        TfiAngleLeft,
        FaAngleLeft,
        PiExportBold,
        BiExport,
        MdOutlineCalculate,
        TiArrowSortedUp,
        TiArrowSortedDown,
        RiDashboardHorizontalFill,
        TbReportSearch,
        MdOutlineShield,
        PiSwapBold,
        GoAlertFill,
        FaUser,
        RiShieldCheckFill,
        RiMoneyDollarCircleLine,
        FaRegCheckCircle,
        GrStatusWarning,
        FaArrowsRotate,
        FaRegTimesCircle,
        FiUserCheck,
        FaMugHot,
        FaRegThumbsDown,
        FaRegThumbsUp,
        FaRegCommentDots,
        IoEyeOutline,
        AiOutlineThunderbolt,
        FaPlus,
        FaRegFileAlt,
        IoShieldCheckmarkOutline,
        RiBarChartBoxFill,
        FaHandsHelping,
        FaLockOpen,
        FaLock,
        FaArrowTrendUp,
        LiaMoneyBillSolid,
        FiUserMinus,
        LuDollarSign,
        LuRefreshCw,
        LuThumbsUp,
        LuThumbsDown,
        LuUser,
        LuFileText,
        LuListChecks,
        LuClock,
        LiaMoneyCheckAltSolid,
        FaDollarSign,
        BsExclamationCircle,
        MdOutlineLogout,
        GrPowerReset,
        BsExclamationTriangle,
        GoCalendar,
        LuMessageSquare,
        HiOutlineBuildingOffice2,
        TbSend,
        FaUserCheck,
        RiFileList3Line,
        LuFilterX,
        LuUserRoundMinus,
        AiOutlineBank,
        FaRegEdit,
        FaCheckCircle,
        FaTimesCircle,
        FaFileAlt,
        FaBalanceScale,
        FaMoneyBillWave,
        GrAttachment,
        LuUserRoundX,
        HiOutlinePrinter,
        BsFillFilterSquareFill,
        IoFilterSharp,
        GrSubtractCircle,
        FiFilePlus,
        TbFileExport,
        FiSend,
        MdPublish,
        MdTaskAlt,
        MdAnalytics,
        HiOutlineCurrencyDollar,
        RxHome,
        LuUsersRound,
        LuFileBadge,
        BsThreeDotsVertical,
        FaRegAddressCard,
        PiUsers,
        AiOutlinePhone,
        FaRegHeart,
        RiFileCloseLine,
        MdChevronRight,
        MdChevronLeft,
        HiOutlineLightningBolt,
        HiOutlineUser,
        HiOutlineClipboardList,
        FaRegCopy,
        HiOutlineSquares2X2,
        FaIndianRupeeSign,
        TbUsersMinus,
        CiShoppingCart,
        FaTrophy,
        ImStatsBars,
        AiOutlineCloudUpload,
        LuFileUser,
        IoSpeedometerOutline,
        AiOutlineDashboard,
        FaCog,
        GoGear,
        TbUserPlus,
        SlOrganization, CiTrophy, FiTool, CiGift, AiOutlineSync, AiOutlineCrown, GoPasskeyFill
    };

    const IconComponent = iconComponents[iconName];

    if (!IconComponent) return null; // fail-safe if iconName is invalid

    const iconElement = (
        <IconComponent
            className={className}
            type={iconName}
            style={{
                fontSize: iconSize,
                color: disabled ? "#bfbfbf" : color, // dim color when disabled
                background: background,
                cursor: disabled ? "not-allowed" : "pointer",
                opacity: disabled ? 0.5 : 1,
                ...style,
            }}
            onMouseEnter={!disabled ? onHoverIconEnter : undefined}
            onMouseLeave={!disabled ? onHoverIconLeave : undefined}
            onClick={!disabled ? onclickIcon : undefined}
            spin={spin}
        />
    );

    return (
        <div
        // className="flex justify-center items-center"
        >
            {showToolTip ? (
                <Tooltip
                    title={toolTipLabel}
                    color={toolTipColor}
                    placement={toolTipPlacement}
                    overlayInnerStyle={{
                        fontSize: "11px",
                        maxWidth: "250px", // you can control width too
                    }}
                >
                    {iconElement}
                </Tooltip>
            ) : (
                iconElement
            )}
        </div>
    );
    // return (
    //   <div className="flex justify-center items-center">
    //     {showToolTip ? (
    //       <Tooltip
    //         title={toolTipLabel}
    //         color={toolTipColor}
    //         overlayInnerStyle={{
    //           fontSize: "11px",
    //           maxWidth: "250px",
    //         }}
    //       >
    //         {loading ? (
    //           <LoadingOutlined
    //             style={{
    //               fontSize: iconSize,
    //               color,
    //               ...style,
    //             }}
    //             spin
    //           />
    //         ) : (
    //           iconElement
    //         )}
    //       </Tooltip>
    //     ) : (
    //       loading ? (
    //         <LoadingOutlined
    //           style={{
    //             fontSize: iconSize,
    //             color,
    //             ...style,
    //           }}
    //           spin
    //         />
    //       ) : (
    //         iconElement
    //       )
    //     )}
    //   </div>
    // );
}

export default DynamicIconComponent;
